name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: BloomAshenvaleTracker.lua
          args: "--no-color -q"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

  publish:
    needs: check
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
          
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Create GitHub release
        run: >
          gh release create ${{github.ref_name}}
          --verify-tag
          releases/${{github.ref_name}}/BloomAshenvaleTracker-${{github.ref_name}}.zip
          releases/${{github.ref_name}}/release.json

      - name: Upload CurseForge
        run: sh upload-cf.sh ${{github.ref_name}}
